In [1]:
import os
import pandas as pd
import xlsxwriter

## TODAS LAS FOTOS

In [3]:
path_imagenes= '/media/leandro/Volumen1TB/Lean/Analizador_imagenes_calcio/Luis/seleccion/'
experiments = os.listdir(path_imagenes)
df = []
for experiment in experiments:
    folders = os.listdir(path_imagenes + experiment + '/')

    for folder in folders:
        files = os.listdir(path_imagenes + experiment + '/' + folder + '/')
        files = [file for file in files if 'tif' in file]
        for file in files:
            df.append([experiment,folder,file[:-4]])
df = pd.DataFrame(df, columns = ['experimento', 'carpeta', 'foto'])

NotADirectoryError: [Errno 20] Not a directory: '/media/leandro/Volumen1TB/Lean/Analizador_imagenes_calcio/Luis/seleccion/tabulado.csv/'

In [5]:
df.to_csv(path_imagenes + 'tabulado.csv')

In [64]:
path = '/media/leandro/Volumen1TB/Lean/Analizador_imagenes_calcio/Luis/'
tabulado_original = pd.read_csv(path + 'tabulado')
del tabulado_original['Unnamed: 0']
tabulado_original.head()

  experimento        célula          foto tratamiento  frecuencia
0   010719SEL  010719ctrol1  ctrol1b0.tif          VK         1.0
1   010719SEL  010719ctrol1  ctrol1a0.tif          VK         5.0
2   010719SEL     010719VK3   vk3b002.tif          VK         5.0
3   010719SEL     010719VK3   vk3a000.tif          VK         1.0
4   010719SEL     010719VK7   vk7b000.tif          VK         1.0

In [6]:
cel = []
photo = []
for name in file_tabulado['photo_name']:
    cel.append(name.split('_')[0])
    photo.append(name.split('_')[3].split('.')[0])
file_tabulado['célula'] = cel
file_tabulado['foto'] = photo
del file_tabulado['photo_name']

file_tabulado.to_csv(path + 'tabulado_parceado.csv')

In [66]:
path = '/media/leandro/Volumen1TB/Lean/Analizador_imagenes_calcio/Luis/analisis/json_nuevos/'
path_originales = '/media/leandro/Volumen1TB/Lean/Analizador_imagenes_calcio/Luis/'
tabulado_original = pd.read_csv(path_originales + 'tabulado')
file_tabulado = pd.read_csv(path + 'tabulado_parceado.csv')
tabulado = pd.read_csv(path_imagenes + 'tabulado.csv')
del file_tabulado['Unnamed: 0']
del file_tabulado['Unnamed: 0.1']
del tabulado['Unnamed: 0']
del tabulado_original['Unnamed: 0']
print(file_tabulado.head())
print(tabulado.head())
print(tabulado_original.head())

  tratamiento  frecuencia    célula      foto
0          vk         3.0    311019   vk2b000
1           c         4.0    171019    c1c000
2          vk         1.0    060121  vk12a000
3           c         3.0  031019c4    c4c000
4          vk         3.0    171019   vk3b000
  experimento   carpeta    foto
0   031019Sel  031019c2  c2c000
1   031019Sel  031019c2  c2d000
2   031019Sel  031019c2  c2f000
3   031019Sel  031019c2  c2e000
4   031019Sel  031019c2  c2b000
  experimento        célula          foto tratamiento  frecuencia
0   010719SEL  010719ctrol1  ctrol1b0.tif          VK         1.0
1   010719SEL  010719ctrol1  ctrol1a0.tif          VK         5.0
2   010719SEL     010719VK3   vk3b002.tif          VK         5.0
3   010719SEL     010719VK3   vk3a000.tif          VK         1.0
4   010719SEL     010719VK7   vk7b000.tif          VK         1.0

In [72]:
df_tabulado = pd. DataFrame()
for line in range(0,len(tabulado)):
    filter_file_tabulado1 = file_tabulado[file_tabulado['célula'].str.contains(tabulado['carpeta'][line])]
    filter_file_tabulado2 = filter_file_tabulado1[filter_file_tabulado1['foto'].str.contains(tabulado['foto'][line])]
    filter_tabulado_original1 = tabulado_original[tabulado_original['célula'].str.contains(tabulado['carpeta'][line])]
    filter_tabulado_original2 = filter_tabulado_original1[filter_tabulado_original1['foto'].str.contains(tabulado['foto'][line])]
    df_tabulado = df_tabulado.append(pd.concat([pd.DataFrame(tabulado.loc[line]).T.reset_index(drop=True), filter_file_tabulado2[['tratamiento','frecuencia']].reset_index(drop=True), filter_tabulado_original2[['tratamiento','frecuencia']].reset_index(drop=True)], axis=1),ignore_index = True)

In [73]:
df_tabulado.head()

,experimento,carpeta,foto,tratamiento,frecuencia,tratamiento,frecuencia
0,031019Sel,031019c2,c2c000,NaN,NaN,C,NaN
1,031019Sel,031019c2,c2d000,NaN,NaN,C,NaN
2,031019Sel,031019c2,c2f000,NaN,NaN,C,NaN
3,031019Sel,031019c2,c2e000,NaN,NaN,C,NaN
4,031019Sel,031019c2,c2b000,c,NaN,C,NaN

In [74]:
df_tabulado.to_csv(path_imagenes + 'tabulado_imagenes.csv')

In [2]:
path_imagenes = '/media/leandro/Volumen1TB/Lean/Analizador_imagenes_calcio/Luis/seleccion/'
df_tabulado = pd.read_csv(path_imagenes + 'tabulado_imagenes.csv')
del df_tabulado['Unnamed: 0']

In [3]:
df_tabulado.head()

  experimento   carpeta    foto tratamiento  frecuencia  dosis
0   031019Sel  031019c2  c2c000           c           3      0
1   031019Sel  031019c2  c2d000           c           4      0
2   031019Sel  031019c2  c2e000           c           5      0
3   031019Sel  031019c2  c2b000           c           1      0
4   031019Sel  031019c3  c3c000           c           3      0

### Control de JSON

In [29]:
path_json = '/media/leandro/Volumen1TB/Lean/Analizador_imagenes_calcio/Luis/analisis/jsons/'
json_files = os.listdir(path_json)
json_in = []
for row in range(0,len(df_tabulado)):
    json_exp = json_files[row].split('_')[0][:6]
    print(json_exp)
    json_foto = json_files[row].split('_')[-1][:-5]
    filter_df_tabulado1 = df_tabulado[df_tabulado['experimento'].str.contains(json_exp)]
    filter_df_tabulado2 = filter_df_tabulado1[filter_df_tabulado1['foto'].str.contains(json_foto)]
    if filter_df_tabulado2.empty:
        json_in.append(0)
    else:
        json_in.append(1)
df_tabulado['json_in'] = json_in

311019
171019
200121
050320
050320
060121
031019
171019
180221
050320
200121
180221
071119
220119
060121
050320
060320
010719
060320
311019
060121
070119
200121
120121
050320
031019
060320
060121
171019
200121
050320
060121
050320
031019
010819
031019
031019
060121
050320
230819
060121
050320
171019
200121
171019
060121
230819
230819
120121
060320
071119
230819
010719
180221
060121
200121
171019
060121
031019
180221
170719
031019
060320
060121
071119
060121
070119
120121
230819
060121
311019
200121
060121
170221
071119
060320
120121
171019
120121
200121
060121
060320
050320
050320
060121
230819
171019
170719
120121
050320
071119
060320
120121
180221
060121
060320
031019
171019
170719
171019
060320
060320
060320
050320
230819
311019
031019
180221
050320
060121
180221
060121
060320
060320
060121
071119
050320
060121
010819
060320
060121
060121
060121
230819
060320
170719
200121
060121
070119
311019
070119
050320
060121
050320
171019
060320
071119
060320
071119
120121
170719
060320
060121
050320
060121
050320
070119
060121
120121
060121
031019
180221
071119
031019
170719
010819
311019
120121
230819
070119
170221
200121
060320
180221
060121
060121
060121
230819
050320
060320
071119
121218
060121
171019
050320
031019
200121
170221
071119
031019
120121
050320
010719
060320
171019
120121
230819
071119
050320
311019
060121
060320
060121
311019
171019
180221
170221
070119
180221
200121
010719
180221
060121
220119
060320
060320
311019
060320
170719
060320
060320
010719
060121
170221
311019
060121
060320
060121
180221
010719
180221
071119
060121
060121
170719
220119
060121
010819
071119
060121
060320
060320
200121
170719
230819
070119
311019
060320
050320
060121
171019
060121
121218
131218
200121
200121
200121
031019
311019
170719
060320
170719
060320
031019
200121
200121
050320
200121
060121
171019
060320
120121
230819
060121
060121
171019
060121
060121
010719
060121
010719
071119
060121
060320
060320
311019
031019
031019
031019
200121
311019
180221
010719
060121
060320
170221
031019
050320
031019
230819
311019
311019
120121
311019
060121
170719
060121
180221
060121
230819
180221
060320
171019
060320
050320
311019
060320
010819
311019
230819
050320
200121
230819
120121
031019
060320
060121
060320
060121
060121
060121
070119
200121
031019
171019
170719
200121
010719
050320
170221
200121
120121
200121
170719
220119
060320
050320
200121
230819
230819
050320
170221
010819
050320
200121
120121
071119
060320
180221
230819
200121
071119
050320
071119
050320
171019
311019
200121
060121
230819
010719
171019
010719
200121
050320
200121
060320
170221
060121
031019
200121
120121
170221
200121
200121
311019
071119
060121
311019
060121
120121
060121
120121
070119
060121
311019
060121
311019

In [30]:
print(df_tabulado['json_in'].sum())
print(len(df_tabulado['json_in']))

288
388

In [31]:
df_tabulado[df_tabulado['json_in']==0]

    experimento       carpeta     foto tratamiento  frecuencia  json_in
5     031019Sel      031019c3   c3d000           c           4        0
13    031019Sel      031019c4   c4c000           c           3        0
14    031019Sel      031019c4   c4b000           c           1        0
20       180221        180221  vk2c000          vk           4        0
27       180221        180221  vk1a000          vk           1        0
..          ...           ...      ...         ...         ...      ...
377   171019sel   171019c6sel   c6a000           c           1        0
379   070119Sel  070119Ctrol3   c3a001           c           1        0
381   070119Sel  070119Ctrol4   c4b000           c           5        0
384   070119Sel  070119Ctrol6   c6b000           c           5        0
386   070119Sel  070119Ctrol5   c5a001           c           1        0

[100 rows x 6 columns]

### Amplitud normalizada

In [79]:
for i in range (0,len(file_tabulado)):
    try:
        cell = file_tabulado['célula'][i]
        photo = file_tabulado['foto'][i]
        wc = pd.read_csv(path + 'whole_cell/' + cell + '_analysis_result_' + photo + '.json.csv', sep = '\t', index_col=0)
        ampl = pd.read_csv(path + 'amplitudes/' + cell + '_analysis_result_' + photo + '.jsonamplitudes.csv', sep = '\t', index_col=0)
        local_min = pd.read_csv(path + 'min_peaks_intensities/' + cell + '_analysis_result_' + photo + '.jsonmin_peaks_intensities.csv', sep = '\t', index_col=0)
        df = pd.DataFrame()
        if file_tabulado['frecuencia'][i]==1:
            df['Transient1'] =  ampl['transient1']*local_min['transient1']/wc['Transient1'].iloc[3]
            df['Transient2'] =  ampl['transient2']*local_min['transient2']/wc['Transient2'].iloc[3]
            df.to_excel(path + 'amplitudes_norm/' + cell + '_' + photo + '.xlsx', engine='xlsxwriter')
        elif file_tabulado['frecuencia'][i]==5:
            file1 = file_tabulado[(file_tabulado['célula']==cell) & (file_tabulado['frecuencia']==1)]
            file1 = file1.reset_index(drop=True)
            wc1 = pd.read_csv(path + 'whole_cell/' + file1['célula'][0] + '_analysis_result_' + file1['foto'][0][:-3] + 'json.csv', sep = '[,\t]', index_col=0)
            df['Transient1'] =  ampl['transient1']*local_min['transient1']/wc1['Transient1'].iloc[3]
            df['Transient2'] =  ampl['transient2']*local_min['transient2']/wc1['Transient2'].iloc[3]
            df.to_excel(path + 'amplitudes_norm/' + cell + '_' + photo + '.xlsx', engine='xlsxwriter')
        else:
            pass
    except FileNotFoundError:
        pass

<ipython-input-79-80ad4218a009>:16: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  wc1 = pd.read_csv(path + 'whole_cell/' + file1['célula'][0] + '_analysis_result_' + file1['foto'][0][:-3] + 'json.csv', sep = '[,\t]', index_col=0)
<ipython-input-79-80ad4218a009>:16: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  wc1 = pd.read_csv(path + 'whole_cell/' + file1['célula'][0] + '_analysis_result_' + file1['foto'][0][:-3] + 'json.csv', sep = '[,\t]', index_col=0)
<ipython-input-79-80ad4218a009>:16: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  wc1 = pd.read_csv(path + 'whole_cell/' + file1['célula'][0] + '_analysis_result_' + file1['foto'][0][:-3] + 'json.csv', sep = '[,\t]', index_col=0)
<ipython-input-79-80ad4218a009>:16: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  wc1 = pd.read_csv(path + 'whole_cell/' + file1['célula'][0] + '_analysis_result_' + file1['foto'][0][:-3] + 'json.csv', sep = '[,\t]', index_col=0)
<ipython-input-79-80ad4218a009>:16: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  wc1 = pd.read_csv(path + 'whole_cell/' + file1['célula'][0] + '_analysis_result_' + file1['foto'][0][:-3] + 'json.csv', sep = '[,\t]', index_col=0)
<ipython-input-79-80ad4218a009>:16: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  wc1 = pd.read_csv(path + 'whole_cell/' + file1['célula'][0] + '_analysis_result_' + file1['foto'][0][:-3] + 'json.csv', sep = '[,\t]', index_col=0)
<ipython-input-79-80ad4218a009>:16: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  wc1 = pd.read_csv(path + 'whole_cell/' + file1['célula'][0] + '_analysis_result_' + file1['foto'][0][:-3] + 'json.csv', sep = '[,\t]', index_col=0)
<ipython-input-79-80ad4218a009>:16: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  wc1 = pd.read_csv(path + 'whole_cell/' + file1['célula'][0] + '_analysis_result_' + file1['foto'][0][:-3] + 'json.csv', sep = '[,\t]', index_col=0)
<ipython-input-79-80ad4218a009>:16: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  wc1 = pd.read_csv(path + 'whole_cell/' + file1['célula'][0] + '_analysis_result_' + file1['foto'][0][:-3] + 'json.csv', sep = '[,\t]', index_col=0)
<ipython-input-79-80ad4218a009>:16: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  wc1 = pd.read_csv(path + 'whole_cell/' + file1['célula'][0] + '_analysis_result_' + file1['foto'][0][:-3] + 'json.csv', sep = '[,\t]', index_col=0)

KeyError: 0

In [ ]:
path = '/media/leandro/Volumen1TB/Lean/Analizador_imagenes_calcio/Luis/analisis/json_nuevos/amplitudes_norm/'
experiments = os.listdir(path)
df = pd.DataFrame()
for experiment in experiments:
    folders = os.listdir(path + experiment + '/')
    list_folders = []
    for folder in folders:
        files = os.listdir(path + experiment + '/' + folder + '/')
        dic_files = {}
        for file in files:
            dic_files [folder] = [file for file in files if 'tif' in file]
        list_folders.append(dic_files)